### ISSUE TITLE
argparse error

### ISSUE THREAD

**Issue by mooreryan** [sej917/BEAR#4]
When trying to run `generate_reads.py`,

```
$ generate_reads.py --help
```

This error occurs

```
Traceback (most recent call last):
  File "generate_reads.py", line 18, in <module>
    parser.add_argument('-d', metavar='<direction_switch>', action='store_true', dest="direction", help="Use this switch to generate reads in both forward and reverse orientations" )
  File "/usr/lib64/python2.7/argparse.py", line 1281, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'metavar'
```

(Python version 2.7.5)

**Comment by mooreryan** [comment]
Pull request #5 fixes this.
